/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.query.Query;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QueryFactory;
import org.apache.jena.query.ResultSet;
import org.apache.jena.query.ResultSetFormatter;
import org.apache.jena.rdf.model.ModelFactory;
import transaccionesOWL.transaccionesOWL;

/**
 *
 * @author dyyysof
 */
public class INICIO extends javax.swing.JFrame {

    //INICIALIZAR JLIST MEDICO
    
    /**
     * Creates new form INICIO
     */
    public INICIO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void inicializarTabla(JTable j1, String[] cabecera, Object[] row){
        DefaultTableModel model = new DefaultTableModel(cabecera,0);
        j1.setModel(model);
        model.addRow(row);
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabMedico = new javax.swing.JTabbedPane();
        opcMedicinas = new javax.swing.JTabbedPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtMedicinas = new javax.swing.JTable();
        opcCentroSalud = new javax.swing.JTabbedPane();
        scroolbar2 = new javax.swing.JScrollPane();
        jtCentroSalud = new javax.swing.JTable();
        opcAreaEsp = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtAreaEspecialidad = new javax.swing.JTable();
        opcPacientes = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtPacientes = new javax.swing.JTable();
        opcTratamiento = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtTratamiento = new javax.swing.JTable();
        opcEspecialidades = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtEspecialidades = new javax.swing.JTable();
        opcEnfermedades = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEnfermedades = new javax.swing.JTable();
        opcMedicos = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMedicos = new javax.swing.JTable();
        opcConsultas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("PROYECTO - Gestión de ontologías para un sistema de consultas inteligentes");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("aplicadas a procesos de Vacunación en el Ecuador contra el Covid 19.");

        tabMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMedicoMouseClicked(evt);
            }
        });

        jtMedicinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jtMedicinas);

        opcMedicinas.addTab("tab1", jScrollPane7);

        tabMedico.addTab("MEDICINAS", opcMedicinas);

        jtCentroSalud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroolbar2.setViewportView(jtCentroSalud);

        opcCentroSalud.addTab("tab1", scroolbar2);

        tabMedico.addTab("CENTRO SALUD", opcCentroSalud);

        jtAreaEspecialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jtAreaEspecialidad);

        opcAreaEsp.addTab("tab1", jScrollPane6);

        tabMedico.addTab("ÁREA ESPECIALIDAD", opcAreaEsp);

        jtPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jtPacientes);

        opcPacientes.addTab("tab1", jScrollPane5);

        tabMedico.addTab("PACIENTES", opcPacientes);

        jtTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtTratamiento);

        opcTratamiento.addTab("tab1", jScrollPane4);

        tabMedico.addTab("TRATAMIENTO", opcTratamiento);

        jtEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtEspecialidades);

        opcEspecialidades.addTab("tab1", jScrollPane3);

        tabMedico.addTab("ESPECIALIDADES", opcEspecialidades);

        jtEnfermedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtEnfermedades);

        opcEnfermedades.addTab("tab1", jScrollPane2);

        tabMedico.addTab("ENFERMEDADES", opcEnfermedades);

        opcMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcMedicosMouseClicked(evt);
            }
        });

        jtMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtMedicos);
        jtMedicos.getAccessibleContext().setAccessibleName("jtMedico");

        opcMedicos.addTab("tab1", jScrollPane1);

        tabMedico.addTab("MEDICOS", opcMedicos);
        opcMedicos.getAccessibleContext().setAccessibleName("pnMedicos");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Qué personal de salud se encuentra en un centro de salud?", "¿Qué áreas de especialidad tiene un centro de salud?", "¿Qué especialidad tiene un personal de salud ?", "¿Qué áreas de especialidad pertenece a un centro de salud XXX ?", "¿A qué  área de salud  pertenece el personal de salud con nombre XXX?", "¿Qué pacientes menores de 20 años han sido atendidos por un personal de salud XXX?", "¿Qué medicinas ha recetado un personal de salud?" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        opcConsultas.addTab("tab1", jPanel2);

        tabMedico.addTab("CONSULTAS", opcConsultas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(tabMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tabMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
        );

        tabMedico.getAccessibleContext().setAccessibleName("pnEnfermedades");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Desarrollado por Stalin Herrera, Mateo Granja & Daniel Yánez");

        jLabel4.setText("Todos los derechos reservados 2022 (C)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMedicoMouseClicked
        //INICIALIZAR TODAS LAS TABLAS
        transaccionesOWL to = new transaccionesOWL();
        ResultSet r = to.primeraConsulta();
        
        
        
        //TABLA MEDICINAS
        String[] tblHeadMedicinas = {"codigo","nombre","cedula","edad"};
        DefaultTableModel model = new DefaultTableModel(tblHeadMedicinas,0);
        jtMedicinas.setModel(model);
        //Object[] rowMedicinas = { "1", "Acetaminofen","Paracetamol" };
        //model.addRow(rowMedicinas);
        to.ConstructionTable(r, tblHeadMedicinas, model, jtMedicinas);
        
        
        
        
        
        //CENTRO DE SALUD
        String[] tblHeadCentro = {"Código","Nombre","Capacidad"," Ubicación","Ciudad"};
        Object[] rowCentro = { "1", "IESS Riobamba","800","Av. José de Sucre", "Riobamba" };
        inicializarTabla(jtCentroSalud,tblHeadCentro,rowCentro);
        
        


        //AREA DE ESPECIALIDAD
        String[] tblHeadareaEsp={"Código","Nombre","Descripción"};
        Object[] rowareaEsp = { "1", "Alergología","Tratamiento de alergias" };
        inicializarTabla(jtAreaEspecialidad,tblHeadareaEsp,rowareaEsp);
        
        
        //PACIENTES
        String[] tblHeadPaciente={"Código","Nombre","Edad"," Cédula"};
        Object[] rowPaciente = { "1", "Jose ","15","0604402305" };
        inicializarTabla(jtPacientes,tblHeadPaciente,rowPaciente);
            

        //TRATAMIENTO
        String[] tblHeadTratamiento={"Código","Descripción"};
        Object[] rowTratamiento = { "1", "2 veces al día" };
        inicializarTabla(jtTratamiento,tblHeadTratamiento,rowTratamiento);

        //ESPECIALIDADES
        String[] tblHeadEspecialidad={"Código","Nombre"};
        Object[] rowEspecialidad = { "1", "Alergología"};
        inicializarTabla(jtEspecialidades,tblHeadEspecialidad,rowEspecialidad);


        //ENFERMEDADES
         String[] tblHeadEnfermedades={"Código","Nombre"};
        Object[] rowEnfermedades = { "1", "COVID-19" };
        inicializarTabla(jtEnfermedades,tblHeadEnfermedades,rowEnfermedades);

        //PERSALUD
        
        String[] tblHead={"Codigo","Nombre","Cedula","Edad"};
        
        //conectarse al owl y hacer la consulta
        
        Object[] row = { "1", "Juan","0604402305","16" };
        inicializarTabla(jtMedicos,tblHead,row);
        


        //CONSULTAS
        
        
        
    }//GEN-LAST:event_tabMedicoMouseClicked

    
    
    
    
    private void opcMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcMedicosMouseClicked
        
    }//GEN-LAST:event_opcMedicosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        

        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO().setVisible(true);
            }
        });
        
        OntModel model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM); model.read("/home/dyyysof/Documents/ont.owl","RDF/XML");
        
        System.out.println("PRUEBA ONTOLOGÍAS");
        String queryString = "PREFIX ont: <http://www.semanticweb.org/dyyysof/ontologies/2022/1/untitled-ontology-25#>" +
                             "SELECT  ?area_especialidad ?centro" + 
                             "		WHERE {" +
                             "				?cen ont:tiene_are ?esp."+
                             "				?esp ont:nombre ?area_especialidad."+
                             "				?cen ont:nombre ?centro."+
                             "}";
        
        Query query = QueryFactory.create(queryString);
        QueryExecution qe = QueryExecutionFactory.create(query,model);
        try{
            ResultSet results = qe.execSelect();
            ResultSetFormatter.out(System.out, results, query);
            
        }finally{
            qe.close();
        }
        
        
        
        
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jtAreaEspecialidad;
    private javax.swing.JTable jtCentroSalud;
    private javax.swing.JTable jtEnfermedades;
    private javax.swing.JTable jtEspecialidades;
    private javax.swing.JTable jtMedicinas;
    private javax.swing.JTable jtMedicos;
    private javax.swing.JTable jtPacientes;
    private javax.swing.JTable jtTratamiento;
    private javax.swing.JTabbedPane opcAreaEsp;
    private javax.swing.JTabbedPane opcCentroSalud;
    private javax.swing.JTabbedPane opcConsultas;
    private javax.swing.JTabbedPane opcEnfermedades;
    private javax.swing.JTabbedPane opcEspecialidades;
    private javax.swing.JTabbedPane opcMedicinas;
    private javax.swing.JTabbedPane opcMedicos;
    private javax.swing.JTabbedPane opcPacientes;
    private javax.swing.JTabbedPane opcTratamiento;
    private javax.swing.JScrollPane scroolbar2;
    private javax.swing.JTabbedPane tabMedico;
    // End of variables declaration//GEN-END:variables
}
